buildscript {
    ext {
        cleanArchitectureVersion = '4.1.0'
        springBootVersion = '4.0.2'
        sonarVersion = '7.2.2.6593'
        jacocoVersion = '0.8.14'
        pitestVersion = '1.19.0-rc.3'
        lombokVersion = '1.18.42'
    }
}

plugins {
    id 'co.com.bancolombia.cleanArchitecture' version "${cleanArchitectureVersion}"
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'info.solidsoft.pitest' version "${pitestVersion}" apply false
    id 'org.sonarqube' version "${sonarVersion}"
    id 'jacoco'
}

sonar {
    def modules = subprojects.projectDir.collect { "${it.toString().replace(project.projectDir.toString() + "/", "")}" }
    properties {
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.modules", "${modules.join(',')}"
        property "sonar.sources", "src,deployment,settings.gradle,main.gradle,build.gradle,${modules.collect { "${it}/build.gradle" }.join(',')}"
        property "sonar.exclusions","**/MainApplication.java"
        property "sonar.tests", "src/test"
        property "sonar.java.binaries", "**/build/classes/java/main"
        property "sonar.junit.reportsPath", "**/build/test-results/test"
        property "sonar.java.coveragePlugin", "jacoco"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacocoMergedReport/jacocoMergedReport.xml"
        property "sonar.pitest.reportPaths", "build/reports/pitest/mutations.xml"
        property "sonar.externalIssuesReportPaths", "build/issues.json"
    }
}

apply from: './main.gradle'

if (!tasks.findByName("jacocoMergedReport")) {
    tasks.register("jacocoMergedReport", JacocoReport) {
        group = "Reporting"
        description = "Generates a merged Jacoco report for all subprojects"

        dependsOn subprojects.findAll { it.tasks.findByName('test') != null }.collect { it.tasks.test }

        executionData files(subprojects.collect { file("${it.buildDir}/jacoco/test.exec") })

        subprojects.each { subproject ->
            def mainSrc = file("${subproject.projectDir}/src/main/java")
            def classesDir = file("${subproject.buildDir}/classes/java/main")
            if (mainSrc.exists() && classesDir.exists()) {
                sourceDirectories.from files(mainSrc)
                classDirectories.from files(classesDir)
            }
        }

        reports {
            xml.required = true
            html.required = true
            csv.required = false
        }
    }
}

tasks.withType(JacocoReport).matching { it.name == "jacocoTestReport" }.configureEach {
    finalizedBy("jacocoMergedReport")
}

