buildscript {
    ext {
        cleanArchitectureVersion = '4.1.0'
        springBootVersion = '4.0.2'
        sonarVersion = '7.2.2.6593'
        jacocoVersion = '0.8.14'
        pitestVersion = '1.19.0-rc.3'
        lombokVersion = '1.18.42'
    }
}

plugins {
    id 'co.com.bancolombia.cleanArchitecture' version "${cleanArchitectureVersion}"
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'info.solidsoft.pitest' version "${pitestVersion}" apply false
    id 'org.sonarqube' version "${sonarVersion}"
    id 'jacoco'
}

sonar {
    def modules = subprojects.projectDir.collect { "${it.toString().replace(project.projectDir.toString() + "/", "")}" }
    properties {
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.modules", "${modules.join(',')}"
        property "sonar.sources", "src,deployment,settings.gradle,main.gradle,build.gradle,${modules.collect { "${it}/build.gradle" }.join(',')}"
        property "sonar.exclusions","**/MainApplication.java"
        property "sonar.tests", "src/test"
        property "sonar.java.binaries", "**/build/classes/java/main"
        property "sonar.junit.reportsPath", "**/build/test-results/test"
        property "sonar.java.coveragePlugin", "jacoco"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacocoMergedReport/jacocoMergedReport.xml"
        property "sonar.pitest.reportPaths", "build/reports/pitest/mutations.xml"
        property "sonar.externalIssuesReportPaths", "build/issues.json"
    }
}

apply from: './main.gradle'


if (!tasks.named("jacocoMergedReport")) {
    tasks.register("jacocoMergedReport", JacocoReport) {
        dependsOn subprojects.findAll { it.tasks.named('test') }.collect { it.tasks.test }

        executionData fileTree(project.rootDir.absolutePath).include("**/build/jacoco/test.exec")

        subprojects.each { subproject ->
            def mainSrc = "${subproject.projectDir}/src/main/java"
            def output = "${subproject.layout.buildDirectory.get().asFile}/classes/java/main"
            if (file(mainSrc).exists() && file(output).exists()) {
                sourceDirectories.from files(mainSrc)
                classDirectories.from files(output)
            }
        }

        reports {
            xml.required = true
            html.required = true
            csv.required = false
        }
    }
}

tasks.withType(JacocoReport).matching { it.name == "jacocoTestReport" }.configureEach {
    finalizedBy("jacocoMergedReport")
}